### ISSUE TITLE
about code 

### ISSUE THREAD

**Issue by MSL502** [hitzhangyu/FLW-Net#1]
Dear author
I would appreciate it if you could publish the entire code and write a note about the code needing a torch version, etc

**Comment by hitzhangyu** [comment]
代码不能运行么？

**Comment by MSL502** [comment]
是的大佬，pytorch等各种版本都具体写一下可以嘛，一直报各种错误，新错误如下
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mmsys/6f1091c9-4ed8-4a10-a03d-2acef144d2e1/SXY/FLW-Net-main/lowlight_train.py", line 164, in <module>
    train(config)
  File "/media/mmsys/6f1091c9-4ed8-4a10-a03d-2acef144d2e1/SXY/FLW-Net-main/lowlight_train.py", line 89, in train
    loss_2, Loss_ssim = L_recon(enhanced_image,img_highlight)
  File "/home/mmsys/anaconda3/envs/FLW/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/mmsys/6f1091c9-4ed8-4a10-a03d-2acef144d2e1/SXY/FLW-Net-main/Myloss.py", line 33, in forward
    L2 = (1- self.ssim_loss(R_low,high)).mean()
  File "/home/mmsys/anaconda3/envs/FLW/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mmsys/anaconda3/envs/FLW/lib/python3.8/site-packages/pytorch_ssim/__init__.py", line 57, in forward
    return _ssim(img1, img2, window, self.window_size, channel, self.size_average)
  File "/home/mmsys/anaconda3/envs/FLW/lib/python3.8/site-packages/pytorch_ssim/__init__.py", line 18, in _ssim
    mu1 = F.conv2d(img1, window, padding = window_size/2, groups = channel)
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Tensor, groups=int, padding=float), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups

**Comment by hitzhangyu** [comment]
增加了一个pytorch_ssim 文件夹
我的环境配置如下：
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h2bbff1b_1003
ca-certificates           2022.10.11           haa95532_0
certifi                   2022.9.24        py37haa95532_0
cffi                      1.15.1           py37h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.6                    pypi_0    pypi
cryptography              38.0.1           py37h21b164f_0
cuda                      11.7.1                        0    nvidia
cuda-cccl                 11.7.91                       0    nvidia
cuda-command-line-tools   11.7.1                        0    nvidia
cuda-compiler             11.7.1                        0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cuobjdump            11.7.91                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-cuxxfilt             11.7.91                       0    nvidia
cuda-demo-suite           11.8.86                       0    nvidia
cuda-documentation        11.8.86                       0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight-compute       11.8.0                        0    nvidia
cuda-nvcc                 11.7.99                       0    nvidia
cuda-nvdisasm             11.8.86                       0    nvidia
cuda-nvml-dev             11.7.91                       0    nvidia
cuda-nvprof               11.8.87                       0    nvidia
cuda-nvprune              11.7.91                       0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-nvvp                 11.8.87                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-sanitizer-api        11.8.86                       0    nvidia
cuda-toolkit              11.7.1                        0    nvidia
cuda-tools                11.7.1                        0    nvidia
cuda-visual-tools         11.7.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
fastrlock                 0.8.1                    pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
huggingface-hub           0.12.1                   pypi_0    pypi
idna                      3.4              py37haa95532_0
importlib-metadata        6.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
iqa-pytorch               0.1                      pypi_0    pypi
jpeg                      9e                   h2bbff1b_0
kiwisolver                1.4.4                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcurand                 10.3.0.86                     0    nvidia
libcurand-dev             10.3.0.86                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libdeflate                1.8                  h2bbff1b_5
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.4.0                h8a3f274_1
libuv                     1.40.0               he774522_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
mmcv-full                 1.5.0                    pypi_0    pypi
mmdet                     2.15.0                   pypi_0    pypi
mmsegmentation            0.21.0                    dev_0    <develop>
nsight-compute            2022.3.0.22                   0    nvidia
numpy                     1.21.5           py37h7a0a035_3
numpy-base                1.21.5           py37hca35cd5_3
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1q               h2bbff1b_0
packaging                 23.0                     pypi_0    pypi
pillow                    9.2.0            py37hdc2b20a_1
pip                       22.2.2           py37haa95532_0
prettytable               3.6.0                    pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pycocotools-windows       2.0.0.2                  pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1                    py37_1
python                    3.7.13               h6244533_1
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.13.0          py3.7_cuda11.7_cudnn8_0    pytorch
pytorch-cuda              11.7                 h67b0de4_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0                      pypi_0    pypi
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.1           py37haa95532_0
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.5.0           py37haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.39.3               h2bbff1b_0
terminaltables            3.1.10                   pypi_0    pypi
timm                      0.6.12                   pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
torchaudio                0.13.0                   pypi_0    pypi
torchinfo                 1.7.2                    pypi_0    pypi
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.3.0            py37haa95532_0
urllib3                   1.26.12          py37haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2              py37haa95532_2
xz                        5.2.6                h8cc25b3_0
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.2                h19a0ad4_0

**Comment by MSL502** [comment]
感谢大佬

**Comment by SAWRJJ** [comment]
> 感谢大佬

请问你出现的bug解决了么

**Comment by MSL502** [comment]
大佬，Bug解决了。请问大佬您的论文是发表在哪里的，我是在https://paperswithcode.com/task/low-light-image-enhancement/latest这里发现您的论文的，想搜一下您的论文发表在哪里，但是没找到。

**Comment by hitzhangyu** [comment]
现在只放在了arxiv上，还处于在投状态

**Comment by SAWRJJ** [comment]
> 感谢大佬

请问你是怎么修改的呢 我运行出来的结果和你最开始的问题是一样的

**Comment by MSL502** [comment]
预祝大佬一举中顶刊

**Comment by MSL502** [comment]
> > 感谢大佬
> 
> 请问你是怎么修改的呢 我运行出来的结果和你最开始的问题是一样的

就是把作者新添加的文件放进去就行了

**Comment by hitzhangyu** [comment]
> 预祝大佬一举中顶刊
感谢！不是大佬，如果code有用的话写paper时候帮忙引用一下哈！感谢

**Comment by MSL502** [comment]
> 



> > 预祝大佬一举中顶刊
> > 感谢！不是大佬，如果code有用的话写paper时候帮忙引用一下哈！感谢

能引用到大佬的文章，是我的荣幸哈哈。大佬冒昧请问下，要是方便可以留个邮箱等联系方式嘛，在看您的文章，我感觉结构图咋和代码对不起来，也可能我还没领悟到大佬的别具匠心。不方便就算了哈哈哈O(∩_∩)O

**Comment by hitzhangyu** [comment]
hitzhangyu@qq.com
