### ISSUE TITLE
NIQE codes

### ISSUE THREAD

**Issue by Xingshi-tech** [hitzhangyu/FLW-Net#12]
I found some methods online for calculating the NIQE metric, and I used them to test the enhancement results, but the results I got were inconsistent with the ones provided in your paper. If possible, could you please share the code you used to calculate the NIQE?

**Comment by hitzhangyu** [comment]
Niqe code used in paper can be found at [Bovik_NIQE_SPL2013](https://github.com/csjunxu/Bovik_NIQE_SPL2013). You can also use the built-in NIQE program in MATLAB, as long as you ensure that the same program is used for all metrics.

**Comment by Xingshi-tech** [comment]
Thanks！
