### ISSUE TITLE
请问作者，您文章中的test time是如何得到的？

### ISSUE THREAD

**Issue by zmzzz12345** [hitzhangyu/FLW-Net#13]

**Comment by zmzzz12345** [comment]
是运行测试脚本得到的那串数字吗？

**Comment by hitzhangyu** [comment]
就用time.time()来测的时间，比如下边这种：
start = time.time()
#operation1
end_time = (time.time() - start)

**Comment by zmzzz12345** [comment]
感谢回答，请问我该如何得到这个test time呢？运行test脚本吗，但是我运行test脚本得到的结果中的数字与实际不符。

**Comment by zmzzz12345** [comment]
> 就用time.time()来测的时间，比如下边这种： start = time.time() #operation1 end_time = (time.time() - start)

感谢回答，请问我该如何得到这个test time呢？运行test脚本吗，但是我运行test脚本得到的结果中的数字与实际不符。

**Comment by hitzhangyu** [comment]
不符是啥？打印的是整个数据集的时间

**Comment by zmzzz12345** [comment]
> 不符是啥？打印的是整个数据集的时间

0.6013312339782715
the psnr and ssim are tensor(24.6987, device='cuda:0'), tensor(0.8396, device='cuda:0') 
这是我用自带权重在v1上的测试结果，其他指标都符合，但是第一行的测试结果，在不同设备上，会有不同的结果，请问是否跟CPU读取速度相关。

非常感谢你的解答！祝好！
