### ISSUE TITLE
过亮/白色区域增强图片出问题

### ISSUE THREAD

**Issue by TwilightArchon** [hitzhangyu/FLW-Net#15]
大佬，我用你的代码跑LOLV1 和LOLV2,但是跑出来的结果都有些问题，我发现是在亮度过高的区域，增强过后的图片会变成这样：
![low00769](https://github.com/hitzhangyu/FLW-Net/assets/134197144/e874ebca-e429-4fbf-8cfc-3c439d0d5020)

我的猜测是白色太亮了，和原本的颜色加在一起会变成奇奇怪怪的颜色，最后超出了白色，变成了0，就是黑色，但是我不太清楚这要怎么解决，请问大佬遇到过这样的问题吗，感谢！

**Comment by TwilightArchon** [comment]
请问是不是训练的epoch太少了，我才训练了2000个epoch，但是我单独训练LOLV1数据集的时候ssim只能达到0.8，然后我尝试在此基础上用大学习率训练LOLV2数据，然后才能达到和论文里差不多的ssim值 :(

**Comment by TwilightArchon** [comment]
解决了，在增强过后把模型的输出clip到0-1就行了

**Comment by TwilightArchon** [comment]
还有请问一下作者大佬，readme里面对于过饱和/过曝光的图是怎么处理的，是改进了网络结构吗？我用大佬的代码训练，只能处理低亮度图片增强，本身很亮的话就会更亮，感谢！

**Comment by hitzhangyu** [comment]
记不太清了，好像是去掉了L1和SSIM？

**Comment by hitzhangyu** [comment]
reame里边的

**Comment by hitzhangyu** [comment]
可能还改动了一些损失函数

**Comment by TwilightArchon** [comment]
好的，感谢大佬

**Comment by rekkles7** [comment]
> 解决了，在增强过后把模型的输出clip到0-1就行了

请问在哪加，我试过好像不太行
