### ISSUE TITLE
损失函数调整

### ISSUE THREAD

**Issue by TwilightArchon** [hitzhangyu/FLW-Net#16]
关于上一个issue里面，使模型应对过饱和/过曝光的调整，请问张老师有打算把更改过的损失函数更新嘛？或者张老师有打算出一篇新论文，在里面启用新的损失函数吗？我尝试删除SSIM和L1进行训练，仍旧是越来越亮。感谢！

**Comment by hitzhangyu** [comment]
一直没空改论文。太亮的话可以试一下控制全局亮度均值？
微信号 zhangyuhit2，有空可以加微信交流哈！
