### ISSUE TITLE
Bug？Line 250 in Myloss.py

### ISSUE THREAD

**Issue by UlanqabBadGuy** [hitzhangyu/FLW-Net#7]
![image](https://github.com/hitzhangyu/FLW-Net/assets/100698511/7f23f7f1-80fa-43a2-b4f6-b764a775cd36)
Hi, I found that there is something error in the code. Is that  `gradient_orig_abs` instead of `gradient_orig1_abs`?

**Comment by hitzhangyu** [comment]
This is the Eqn. of mine another paper: [Self-supervised low light image enhancement and denoising](https://www.researchgate.net/publication/349683113_Self-supervised_Low_Light_Image_Enhancement_and_Denoising)
