### ISSUE TITLE
训练psnr

### ISSUE THREAD

**Issue by 2665207323** [hitzhangyu/FLW-Net#8]
请问一下作者，为什么我用您给的代码给LOL_v2数据集训练时，PSNR和SSIM的值会从一开始就越来越低直到为负值呢

**Comment by hitzhangyu** [comment]
是不是数据路径有问题啊？没遇到过降低甚至是负的情况



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月22日(周二) 晚上10:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hitzhangyu/FLW-Net] 训练psnr (Issue #8)




 
请问一下作者，为什么我用您给的代码给LOL_v2数据集训练时，PSNR和SSIM的值会从一开始就越来越低直到为负值呢

**Comment by 2665207323** [comment]
> 是不是数据路径有问题啊？没遇到过降低甚至是负的情况
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月22日(周二) 晚上10:13 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [hitzhangyu/FLW-Net] 训练psnr (Issue #8) 请问一下作者，为什么我用您给的代码给LOL_v2数据集训练时，PSNR和SSIM的值会从一开始就越来越低直到为负值呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

可能是吧，后面我用自己的显卡刚开始跑v1和v2数据集没问题，但是a100上还是不行，后面我又重新解压一下v2数据集，路径是：E:\G_disks\DataSet\LOL\LOL_v2\，跑的时候还是一直下降，但我把数据集放到上一级路径就又可以了：E:\G_disks\DataSet\LOL_v2\。而且，我在服务器A100上就算把数据集文件放到项目下面还是不行，但是用A100跑v1数据集就能正常训练和测试，而且v1数据集的存放位置在不在项目里面都可以
